apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nestcon
        image: neromorph/nestapp
        ports:
        - containerPort: 3000
